### ISSUE TITLE
An async response within a websocket handler

### ISSUE THREAD

**Issue by timschwab** [raggi/async_sinatra#45]
I see that you've been looking for a maintainer for like two years, so you might not be answering these anymore. But I thought I might ask. My question is originally posted on Stack Overflow [here](https://stackoverflow.com/questions/45987788/sinatra-using-a-websocket-client-to-respond-to-a-http-request).

Basically, I need to communicate with another server that only uses websockets, which means I need to wait for its messages, then wait for it to close, and then send the HTTP response to the client, based on that information. I'm using async_sinatra for this, but when I call the `body` method within the websocket logic, nothing happens.

**Comment by raggi** [comment]
The problem here is that the websocket client is running your callbacks on some other thread, and this is probably breaking someones thread local somewhere. You're also probably not waiting for the websocket to close before finalizing your response, but I'm on a plane very late at night and not tracing too deep - I haven't touched any of this ruby stuff in years.

You can probably fix your example like this:

``` ruby
require 'sinatra'
require 'sinatra/async'
require 'websocket-client-simple'

set :server, 'thin'

register Sinatra::Async

aget '/' do
    puts 'Request received'

    socketResponse('wss:// ... URL ...', binding)
end

def socketResponse(url, b)
    ws = WebSocket::Client::Simple.connect(url)

    puts 'Connected to web socket'

    ws.on :message do |message|
        puts 'Got message:' + message.to_s
    end

    ws.on :close do
        puts 'WS closed'
        EM.schedule { b.body 'Closed ...' }
    end

    ws.on :open do
        puts 'WS open'

        message = 'A nice message to process'
        ws.send message
        puts 'Sent: ' + message
    end
end
```

But in a modern ruby environment, there's not so much of an advantage to all of this async-ness you have going on. You're probably better off using puma configured with a high thread count. You can go deeper and start doing lazy body yields and so on, but that'll be more complicated. A simple example like this should work:

Note, this is just a plain rack app, written with the `run` line for a config.ru:

``` ruby
class App
  def call(env)
    q = Queue.new

    ws = WebSocket::Client::Simple.connect(url)

    puts 'Connected to web socket'

    ws.on :message do |message|
        puts 'Got message:' + message.to_s
    end

    ws.on :close do
        puts 'WS closed'
        q.push [ 200, {'Content-Type' => 'text/plain'}, [ 'closed' ] ]
    end

    ws.on :open do
        puts 'WS open'

        message = 'A nice message to process'
        ws.send message
        puts 'Sent: ' + message
    end

    q.pop
  end
end
```

HTH

**Comment by timschwab** [comment]
Thank you very much, that was very helpful! I was able to get it working with a few changes.
